Testing
YunoHost-Apps/wetty_ynh pull request #2
Opened 2020-10-19 09:43 UTC by ericgaspar

- Upgrade to v.2.0.2

2020-10-20 22:08 UTC, yalh76 requested changes

2020-10-20 22:08 UTC, yalh76 commented on scripts/upgrade
> +# Create a dedicated NGIN config
```suggestion
# Create a dedicated NGINX config
```

2020-10-20 22:09 UTC, yalh76 approved these changes

2020-10-21 06:30 UTC, merged

2020-10-21 09:54 UTC, Salamandar commented
I'm sorry I have a lot on my plate these times. It'll be quieter in 2 weeks. Sorry for the wait…

2020-10-21 10:16 UTC, ericgaspar commented
No problem. Hope you don't mind me pushing a bunch of commits

2020-10-21 11:42 UTC, Salamandar commented
Yeah, no problem with that ! It's sometimes easier to review. I may squash them in the end.